baseURL: /
title: Grellyd - Graham L. Brown
languageCode: en-ca
theme: kubo_hugo
disableKinds: [RSS, sitemap]
params:
    AuthorName: Graham L. Brown
    GithubUsername: grellyd
    TwitterUsername: grellyd
    LinkedInUsername: grellyd
    SiteName: Grellyd
googleAnalytics: UA-127080315-1
