baseURL: /
title: Graham L. Brown
languageCode: en-ca
theme: kubo
disableKinds: [RSS, sitemap]
params:
    highlight: default
    topmenu: categories
    authorName: Graham L. Brown

GithubUsername: grellyd
TwitterUsername: grellyd
LinkedInUsername: grellyd
