baseURL: /
title: Grellyd - Graham L. Brown
languageCode: en-ca
theme: kubo
disableKinds: [RSS, sitemap]
params:
    AuthorName: Graham L. Brown
    GithubUsername: grellyd
    TwitterUsername: grellyd
    LinkedInUsername: grellyd

